const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('uz-UZ').format(n||0)+' so\'m';
const state=JSON.parse(localStorage.getItem('uzpro1c')||'null')||{screen:'manager',docs:[],postings:[],cash:150000000,bank:480000000,inventory:0,theme:'light'};
function save(){localStorage.setItem('uzpro1c',JSON.stringify(state));$('#saveDot').textContent='● saqlandi';updateStatus()}
function updateStatus(){ $('#docCount').textContent=state.docs.length; $('#postingCount').textContent=state.postings.length; $('#statusMsg').textContent='Готово'; }
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setInspector(title,html){$('#inspectBody').innerHTML=`<div class="inspect-section"><h3>${title}</h3>${html}</div>`}
function inspect(type){
 const data={
  debit:['DEBIT nima?','Aktiv yoki xarajat schyotida ko‘payish odatda <b>Debet</b> tomonida aks etadi. Aniq provodka hisob siyosati va operatsiyaga bog‘liq.'],
  credit:['KREDIT nima?','Passiv yoki daromad schyotida ko‘payish odatda <b>Kredit</b> tomonida aks etadi. Har doim schyotning iqtisodiy mohiyatini tekshiring.'],
  conduct:['Провести nima qiladi?','Hujjatni saqlashdan farqli ravishda “Провести” o‘quv bazasida hujjat asosidagi yozuvlarni registrlarga qo‘llaydi. Keyin hisobot natijasi o‘zgaradi.'],
  register:['Registr nima?','1Cda hujjat natijalari hisob, yig‘ma, ma’lumot va boshqa registrlarda saqlanadi. Hisobotlar shu ma’lumotlardan foydalanadi.'],
  osv:['ОСВ nima?','Oborot-saldo ведомость schyotlar bo‘yicha davr boshidagi saldo, debet/kredit aylanishi va davr oxiridagi saldo nazoratini beradi.'],
  tax:['Soliq nuqtasi','Soliqni o‘rganishda 5 qadam: soliq to‘lovchi → baza → stavka → hisoblash → deklaratsiya/to‘lov. Real stavkani amaldagi qonunchilikdan tekshiring.']};
 const d=data[type]||data.register; setInspector(d[0],`<p>${d[1]}</p><div class="flow"><span>Hujjat</span><span>Provodka</span><span>Registr</span><span>Hisobot</span></div>`)
}
const menu={
 manager:{title:'Руководителю',sub:'Korxona holatini bir oynada nazorat qiling.',render:manager},
 bank:{title:'Банк и касса',sub:'Bank ko‘chirmasi, to‘lov topshiriqlari va kassa operatsiyalari.',render:bank},
 sales:{title:'Продажи',sub:'Mijoz, realizatsiya, qaytarish va debitorlik.',render:sales},
 purchases:{title:'Покупки',sub:'Yetkazib beruvchi, kirim, qarzdorlik va QQS.',render:purchases},
 warehouse:{title:'Склад',sub:'Tovarlar, qoldiq, ko‘chirish va inventarizatsiya.',render:warehouse},
 production:{title:'Производство',sub:'Ishlab chiqarish buyurtmasi va tannarx mantig‘i.',render:production},
 fixed:{title:'ОС и НМА',sub:'Asosiy vositani qabul qilish, amortizatsiya va chiqim.',render:fixed},
 salary:{title:'Зарплата и кадры',sub:'Xodim, oylik, ushlanmalar va soliq.',render:salary},
 operations:{title:'Операции',sub:'Qo‘lda operatsiya, provodka va registr nazorati.',render:operations},
 edo:{title:'ЭДО',sub:'Elektron hujjat aylanishi: yuborish, qabul qilish, status.',render:edo},
 reports:{title:'Отчеты',sub:'ОСВ, balans, foyda-zarar, qarzdorlik va soliq hisobotlari.',render:reports},
 catalogs:{title:'Справочники',sub:'Kontragent, nomenklatura, tashkilot, ombor va schyotlar.',render:catalogs},
 admin:{title:'Администрирование',sub:'Demo baza sozlamalari va o‘quv rejimi.',render:admin},
 home:{title:'Начальная страница',sub:'1Cga o‘xshash to‘liq o‘quv ish stoli.',render:home}
};
function head(m){return `<div class="page-head"><div><h1>${m.title}</h1><p>${m.sub}</p></div><div class="toolbar"><button class="btn" data-help="${m.title}">Что это?</button><button class="btn yellow" id="newDoc">Создать</button></div></div>`}
function manager(){return head(menu.manager)+`<div class="cards"><div class="kpi"><small>Bank hisoblari</small><b>${fmt(state.bank)}</b></div><div class="kpi"><small>Касса</small><b>${fmt(state.cash)}</b></div><div class="kpi"><small>Тovar qoldig‘i</small><b>${fmt(state.inventory)}</b></div><div class="kpi"><small>Hujjatlar</small><b>${state.docs.length}</b></div></div><div class="workspace"><div class="workspace-head"><b>Быстрые действия</b></div><div class="workspace-body"><div class="doc-list"><div class="doc" data-go="sales"><b>Реализация товаров и услуг</b><span>Mijozga sotuv hujjati</span></div><div class="doc" data-go="purchases"><b>Поступление товаров</b><span>Yetkazib beruvchidan kirim</span></div><div class="doc" data-go="bank"><b>Банковская выписка</b><span>Pul harakatini kiritish</span></div><div class="doc" data-go="salary"><b>Начисление зарплаты</b><span>Oylik hisoblash</span></div><div class="doc" data-go="reports"><b>ОСВ</b><span>Natijani tekshirish</span></div><div class="doc" data-go="operations"><b>Операции вручную</b><span>Dt/Kt yozuvini ko‘rish</span></div></div><div class="callout success"><b>O‘quv algoritmi:</b> hujjat yarating → maydonlarni to‘ldiring → Провести → provodkani ko‘ring → registrni tekshiring → hisobotga boring.</div></div></div>`}
function bank(){return head(menu.bank)+`<div class="workspace"><div class="workspace-head"><b>Банк и касса</b><button class="btn" id="openBankDoc">Банковская выписка</button><button class="btn" id="openPayment">Платежное поручение</button><button class="btn" id="openCash">Приходный кассовый ордер</button></div><div class="workspace-body"><div class="two-col"><div class="menu-panel"><button class="active">Банковские выписки</button><button>Платежные поручения</button><button>Кассовые документы</button><button>Эквайринг</button><button>Инвентаризация кассы</button></div><div class="form-panel"><div class="section-tabs"><button class="active">Список</button><button>Проверка</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Дата</th><th>Документ</th><th>Сумма</th><th>Статус</th></tr></thead><tbody>${state.docs.filter(x=>x.type==='bank').map(x=>`<tr data-inspect="register"><td>${x.date}</td><td>${x.name}</td><td class="num">${fmt(x.amount)}</td><td><span class="badge green">Проведен</span></td></tr>`).join('')||'<tr><td colspan="4">Hozircha hujjat yo‘q. “Банковская выписка”ni bosing.</td></tr>'}</tbody></table></div></div></div></div></div>`}
function sales(){return head(menu.sales)+documentForm('sale','Реализация товаров и услуг','Xaridor','ABC MCHJ','Tovar','Printer HP','Miqdor','2','Narx','3000000')+`<div class="workspace"><div class="workspace-head"><b>Продажи: o‘quv tushunchasi</b></div><div class="workspace-body"><div class="flow"><span>Контрагент</span><span>Номенклатура</span><span>Сумма</span><span>Провести</span><span>Dt/Kt</span><span>ОСВ</span></div><p class="side-note">Har bir bosqichni bosing — o‘ngdagi inspector sababini tushuntiradi.</p></div></div>`}
function purchases(){return head(menu.purchases)+documentForm('purchase','Поступление товаров и услуг','Поставщик','XYZ MCHJ','Tovar','Printer HP','Miqdor','10','Narx','2000000')}
function documentForm(type,title,l1,v1,l2,v2,l3,v3,l4,v4){return `<div class="workspace"><div class="workspace-head"><b>${title}</b><span class="badge">Demo hujjat</span></div><div class="workspace-body"><div class="form-grid"><label>Дата</label><div class="field" id="docDate">30.09.2026</div><label>${l1}</label><div class="field" id="f1">${v1}</div><label>${l2}</label><div class="field" id="f2">${v2}</div><label>${l3}</label><div class="field" id="f3">${v3}</div><label>${l4}</label><div class="field" id="f4">${v4}</div><label>Комментарий</label><div class="field" id="f5" contenteditable="true">O‘quv simulyatsiyasi</div></div><div class="form-actions"><button class="btn" data-inspect="register">Записать</button><button class="btn primary" id="conduct" data-type="${type}">Провести</button><button class="btn" id="showPosting">Дт / Кт</button><button class="btn" id="showCode">Код экрана</button></div><div id="resultBox"></div></div></div>`}
function warehouse(){return head(menu.warehouse)+`<div class="workspace"><div class="workspace-head"><b>Остатки товаров</b><button class="btn" id="moveStock">Перемещение</button><button class="btn" id="inventory">Инвентаризация</button></div><div class="workspace-body"><div class="table-wrap"><table class="data-table"><thead><tr><th>Nomenklatura</th><th>Ombor</th><th>Miqdor</th><th>Summa</th></tr></thead><tbody><tr><td>Printer HP</td><td>Asosiy ombor</td><td>10 dona</td><td class="num">${fmt(20000000)}</td></tr><tr><td>Kartrij</td><td>Asosiy ombor</td><td>25 dona</td><td class="num">${fmt(6250000)}</td></tr></tbody></table></div></div></div>`}
function production(){return head(menu.production)+`<div class="workspace"><div class="workspace-body"><div class="callout"><b>Ishlab chiqarish zanjiri:</b> materiallar → ishlab chiqarish → tayyor mahsulot → tannarx → realizatsiya.</div><div class="two-col"><div class="menu-panel"><button class="active">Производство</button><button>Требование-накладная</button><button>Отчет производства</button><button>Расчет себестоимости</button></div><div class="form-panel"><div class="form-grid"><label>Mahsulot</label><div class="field">Stol</div><label>Reja</label><div class="field">50 dona</div><label>Material</label><div class="field">Yog‘och + furnitura</div><label>Tannarx</label><div class="field">Avtomatik hisoblanadi</div></div><div class="form-actions"><button class="btn primary" id="prodDemo">Ishlab chiqarishni o'tkazish</button></div></div></div></div></div>`}
function fixed(){return head(menu.fixed)+documentForm('fixed','Принятие к учету ОС','Контрагент','ABC MCHJ','Объект','Printer HP','Стоимость','3000000','Срок','36 oy')}
function salary(){return head(menu.salary)+`<div class="workspace"><div class="workspace-head"><b>Начисление зарплаты</b><button class="btn" id="salaryDemo">Hisoblash</button></div><div class="workspace-body"><div class="table-wrap"><table class="data-table"><thead><tr><th>Xodim</th><th>Lavozim</th><th>Hisoblangan</th><th>JShDS</th><th>To‘lanadi</th></tr></thead><tbody><tr><td>Ali Valiyev</td><td>Buxgalter</td><td class="num">8 000 000</td><td class="num">960 000</td><td class="num">7 040 000</td></tr><tr><td>Madina Karimova</td><td>Operator</td><td class="num">5 000 000</td><td class="num">600 000</td><td class="num">4 400 000</td></tr></tbody></table></div><div class="callout">O‘quv nuqtasi: ish haqi → ushlanmalar → ish beruvchi soliqlari → to‘lov → hisobot.</div></div></div>`}
function operations(){return head(menu.operations)+`<div class="workspace"><div class="workspace-head"><b>Операция вручную</b></div><div class="workspace-body"><div class="form-grid"><label>Dt schyot</label><div class="field" id="dt">4010</div><label>Kt schyot</label><div class="field" id="kt">9010</div><label>Summa</label><div class="field" id="amount" contenteditable="true">6000000</div><label>Izoh</label><div class="field" contenteditable="true">Realizatsiya demo</div></div><div class="form-actions"><button class="btn primary" id="manualPost">Провести</button><button class="btn" id="postingExplain">Nega Dt/Kt?</button></div><div id="opResult"></div></div></div>`}
function edo(){return head(menu.edo)+`<div class="workspace"><div class="workspace-head"><b>ЭДО — Электронный документооборот</b><button class="btn primary" id="edoSend">Demo yuborish</button></div><div class="workspace-body"><div class="flow"><span>Черновик</span><span>Отправлен</span><span>Доставлен</span><span>Подписан</span><span>Принят</span></div><div class="callout">EDO hujjati 1Cdagi hujjat bilan bog‘lanadi; statusni tekshirish va imzo jarayonini tushunish muhim.</div></div></div>`}
function reports(){return head(menu.reports)+`<div class="workspace"><div class="workspace-head"><b>Отчеты</b><button class="btn primary" id="osv">Сформировать ОСВ</button></div><div class="workspace-body"><div class="doc-list"><div class="doc" data-report="osv"><b>Оборотно-сальдовая ведомость</b><span>Dt/Kt aylanish va saldo</span></div><div class="doc" data-report="balance"><b>Бухгалтерский баланс</b><span>Aktiv / majburiyat / kapital</span></div><div class="doc" data-report="pnl"><b>Прибыли и убытки</b><span>Daromad va xarajat</span></div><div class="doc" data-report="debt"><b>Дебиторка / кредиторка</b><span>Qarzdorlik nazorati</span></div></div><div id="reportResult"></div></div></div>`}
function catalogs(){return head(menu.catalogs)+`<div class="workspace"><div class="workspace-head"><b>Справочники</b></div><div class="workspace-body"><div class="two-col"><div class="menu-panel"><button class="active" data-cat="partners">Контрагенты</button><button data-cat="items">Номенклатура</button><button data-cat="warehouses">Склады</button><button data-cat="accounts">План счетов</button><button data-cat="org">Организации</button></div><div class="form-panel" id="catBody"><div class="table-wrap"><table class="data-table"><thead><tr><th>Nomi</th><th>INN</th><th>Turi</th></tr></thead><tbody><tr><td>ABC MCHJ</td><td>309000000</td><td>Харидор</td></tr><tr><td>XYZ MCHJ</td><td>308000000</td><td>Yetkazib beruvchi</td></tr></tbody></table></div></div></div></div></div>`}
function admin(){return head(menu.admin)+`<div class="workspace"><div class="workspace-body"><div class="callout"><b>Demo rejim:</b> bu laboratoriya real 1C serveriga ulanmaydi. Maqsad — 1Cdagi navigatsiya, hujjat, provodka, registr va hisobotlar orasidagi bog‘lanishni xavfsiz mashq qilish.</div><div class="form-actions"><button class="btn" id="resetDemo">Demo bazani tozalash</button><button class="btn" id="exportDemo">Demo ma'lumotlarini JSON</button></div><pre class="code">1. Разделni tanlang
2. Hujjat yarating
3. Maydonlarni to‘ldiring
4. Провести
5. Dt/Kt ni tekshiring
6. Registrni ko‘ring
7. Hisobotni shakllantiring</pre></div></div>`}
function home(){return head(menu.home)+`<div class="cards"><div class="kpi"><small>1C navigatsiya</small><b>14 bo‘lim</b></div><div class="kpi"><small>O‘quv hujjatlari</small><b>12 tur</b></div><div class="kpi"><small>Registrlar</small><b>Demo</b></div><div class="kpi"><small>Hisobotlar</small><b>4 asosiy</b></div></div><div class="workspace"><div class="workspace-head"><b>1Cni o‘rganish uchun tavsiya etilgan marshrut</b></div><div class="workspace-body"><div class="flow"><span>Справочники</span><span>Покупки</span><span>Склад</span><span>Продажи</span><span>Банк</span><span>Зарплата</span><span>Операции</span><span>Отчеты</span><span>Солиқ</span></div></div></div>`}
function render(screen=state.screen){state.screen=screen;const m=menu[screen]||menu.manager;$('.nav-item.active')?.classList.remove('active');$(`.nav-item[data-screen="${screen}"]`)?.classList.add('active');$('#crumbCurrent').textContent=m.title;$('#screen').innerHTML=m.render();bind();updateStatus()}
function bind(){
 $$('[data-go]').forEach(e=>e.onclick=()=>render(e.dataset.go));
 $$('[data-inspect]').forEach(e=>e.onclick=()=>inspect(e.dataset.inspect));
 $$('[data-report]').forEach(e=>e.onclick=()=>showReport(e.dataset.report));
 $$('[data-help]').forEach(e=>e.onclick=()=>setInspector(e.dataset.help,`<p>Bu bo‘limni 1Cda o‘rganish uchun avval ro‘yxatni ko‘ring, keyin hujjat yarating, so‘ng <b>Провести</b> orqali natijani tekshiring.</p>`));
 $('#newDoc')?.addEventListener('click',()=>{if(['sales','purchases','fixed'].includes(state.screen)){toast('Demo hujjat shakli ochiq — maydonlarni to‘ldiring.')}else if(state.screen==='bank')openBankModal();else toast('Bu bo‘limda demo hujjat tanlang.');});
 $('#conduct')?.addEventListener('click',conduct); $('#showPosting')?.addEventListener('click',()=>inspect('conduct')); $('#showCode')?.addEventListener('click',showCode);
 $('#openBankDoc')?.addEventListener('click',openBankModal); $('#openPayment')?.addEventListener('click',()=>openSimple('Платежное поручение','To‘lov topshirig‘i','Bankdan yetkazib beruvchiga 12 000 000 so‘m to‘lovni demo tarzda kiriting.')); $('#openCash')?.addEventListener('click',()=>openSimple('Приходный кассовый ордер','Kassa kirimi','Kassaga pul kirimini demo tarzda kiriting.'));
 $('#moveStock')?.addEventListener('click',()=>openSimple('Перемещение товаров','Omborlararo ko‘chirish','Tovar bir ombordan ikkinchisiga o‘tkaziladi; qoldiq qiymati o‘zgarmaydi.'));
 $('#inventory')?.addEventListener('click',()=>openSimple('Инвентаризация','Inventarizatsiya','Haqiqiy qoldiqni 1Cdagi qoldiq bilan solishtirishni mashq qiling.'));
 $('#prodDemo')?.addEventListener('click',()=>{toast('Ishlab chiqarish demo hujjati o‘tkazildi');setInspector('Производство','<p>Material sarfi va tayyor mahsulot chiqishi o‘rtasidagi bog‘lanish yaratildi.</p>')});
 $('#salaryDemo')?.addEventListener('click',()=>{toast('Oylik demo hisoblandi');inspect('tax')}); $('#manualPost')?.addEventListener('click',manualPost); $('#postingExplain')?.addEventListener('click',()=>inspect('debit'));
 $('#edoSend')?.addEventListener('click',()=>{toast('EDO demo status: Отправлен → Доставлен');setInspector('ЭДО','<p>Statuslar o‘quv simulyatsiyasi. Real EDO operatori bilan integratsiya emas.</p>')});
 $('#osv')?.addEventListener('click',()=>showReport('osv')); $('#resetDemo')?.addEventListener('click',resetDemo); $('#exportDemo')?.addEventListener('click',exportDemo);
 $$('[data-cat]').forEach(b=>b.onclick=()=>{const names={partners:['ABC MCHJ','XYZ MCHJ'],items:['Printer HP','Kartrij'],warehouses:['Asosiy ombor','Filial ombori'],accounts:['4010','5010','5110','6010','9010'],org:['ABC MCHJ']};$('#catBody').innerHTML=`<div class="table-wrap"><table class="data-table"><tbody>${(names[b.dataset.cat]||[]).map(x=>`<tr><td>${x}</td><td>Demo</td><td>Faol</td></tr>`).join('')}</tbody></table></div>`});
}
function conduct(){const type=$('#conduct').dataset.type;const fields=['f1','f2','f3','f4'].map(id=>$('#'+id)?.textContent.trim());let amount=Number(fields[3]?.replace(/\D/g,''))||0;if(type==='sale'){state.docs.push({type:'sale',name:'Реализация товаров и услуг',date:'30.09.2026',amount});state.postings.push({dt:'4010',kt:'9010',amount});state.inventory=Math.max(0,state.inventory-amount);$('#resultBox').innerHTML=`<div class="callout success"><b>Проведено.</b> Demo: Dt 4010 / Kt 9010 — ${fmt(amount)}.<br>Keyin ОСВga o‘ting va natijani ko‘ring.</div>`}else if(type==='purchase'){state.docs.push({type:'purchase',name:'Поступление товаров и услуг',date:'30.09.2026',amount});state.postings.push({dt:'2910',kt:'6010',amount});state.inventory+=amount;$('#resultBox').innerHTML=`<div class="callout success"><b>Проведено.</b> Demo: Dt 2910 / Kt 6010 — ${fmt(amount)}.</div>`}else{state.docs.push({type, name:'ОС принятие к учету',date:'30.09.2026',amount});state.postings.push({dt:'0100',kt:'6010',amount});$('#resultBox').innerHTML=`<div class="callout success"><b>Проведено.</b> Demo provodka yaratildi.</div>`}save();toast('Проведено — registrlar yangilandi')}
function manualPost(){let a=Number($('#amount').textContent.replace(/\D/g,''))||0;state.postings.push({dt:$('#dt').textContent,kt:$('#kt').textContent,amount:a});state.docs.push({type:'manual',name:'Операция вручную',date:'30.09.2026',amount:a});save();$('#opResult').innerHTML=`<div class="callout success">Dt ${$('#dt').textContent} / Kt ${$('#kt').textContent} — <b>${fmt(a)}</b></div>`;toast('Qo‘lda provodka o‘tkazildi')}
function openBankModal(){openSimple('Банковская выписка','Bank operatsiyasi','Bankdan tushum yoki chiqimni demo tarzda kiriting. “Провести”dan keyin bank qoldig‘i va provodkani tekshiring.',true)}
function openSimple(title,label,text,bank=false){$('#modalBody').innerHTML=`<h2>${title}</h2><p>${text}</p><div class="form-grid"><label>${label}</label><div class="field" id="modalName">ABC MCHJ</div><label>Summa</label><div class="field" id="modalAmount" contenteditable="true">12000000</div></div><div class="form-actions"><button class="btn" id="modalExplain">Bu nima?</button><button class="btn primary" id="modalPost">Провести</button></div><div id="modalResult"></div>`;$('#modal').classList.add('show');$('#modalExplain').onclick=()=>setInspector(title,'<p>'+text+'</p>');$('#modalPost').onclick=()=>{let a=Number($('#modalAmount').textContent.replace(/\D/g,''))||0;state.docs.push({type:bank?'bank':'other',name:title,date:'30.09.2026',amount:a});state.postings.push({dt:bank?'5110':'6010',kt:bank?'4010':'5110',amount:a});if(bank)state.bank+=a;save();$('#modalResult').innerHTML=`<div class="callout success">Проведено. Dt ${bank?'5110':'6010'} / Kt ${bank?'4010':'5110'} — ${fmt(a)}</div>`;toast('Hujjat o‘tkazildi')}}
function showReport(type){const rows=state.postings.map(p=>`<tr><td>${p.dt}</td><td>${p.kt}</td><td class="num">${fmt(p.amount)}</td></tr>`).join('');const title={osv:'Оборотно-сальдовая ведомость',balance:'Бухгалтерский баланс',pnl:'Прибыли и убытки',debt:'Дебиторка / кредиторка'}[type];$('#reportResult').innerHTML=`<div class="workspace" style="margin-top:14px"><div class="workspace-head"><b>${title}</b><span class="badge green">Сформирован</span></div><div class="workspace-body"><table class="data-table"><thead><tr><th>Dt</th><th>Kt</th><th>Сумма</th></tr></thead><tbody>${rows||'<tr><td colspan="3">Hozircha provodka yo‘q. Avval hujjat o‘tkazing.</td></tr>'}</tbody></table><div class="callout">Bu hisobot demo registrlardan tuzildi. Real 1Cda hisobot konfiguratsiya va bazadagi haqiqiy hujjatlarga bog‘liq.</div></div></div>`;inspect('osv')}
function showCode(){openModalCode(`// Demo 1C-style screen
<section class="document-form">
  <label>Контрагент</label>
  <input value="ABC MCHJ">
  <label>Товар</label>
  <input value="Printer HP">
  <button>Провести</button>
</section>

// O‘quv logikasi:
// Hujjat -> Провести -> Dt/Kt -> Registr -> Hisobot`)}
function openModalCode(code){$('#modalBody').innerHTML=`<h2>Ekran kodi</h2><p>Bu kod real 1C konfiguratori emas; laboratoriya interfeysining web prototipi.</p><pre class="code">${code.replace(/</g,'&lt;')}</pre><button class="btn" id="copyCode">Copy</button>`;$('#modal').classList.add('show');$('#copyCode').onclick=()=>{navigator.clipboard?.writeText(code);toast('Kod nusxalandi')}}
function resetDemo(){if(confirm('Demo bazani tozalaysizmi?')){localStorage.removeItem('uzpro1c');location.reload()}}
function exportDemo(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='uzpro-1c-demo.json';a.click()}
$('#hamb').onclick=()=>$('#navrail').classList.toggle('open');$('#closeInspector').onclick=()=>$('#inspector').classList.toggle('collapsed');$('#theme').onclick=()=>document.body.classList.toggle('dark');$('#modalX').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};$('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase();if(q.includes('bank'))render('bank');else if(q.includes('sotuv')||q.includes('realiz'))render('sales');else if(q.includes('xarid'))render('purchases');else if(q.includes('ombor'))render('warehouse');else if(q.includes('hisobot')||q.includes('osv'))render('reports');};$$('.nav-item').forEach(b=>b.onclick=()=>render(b.dataset.screen));$('.home-link').onclick=()=>render('home');
render(state.screen);
